services:
  - type: worker
    name: whatsapp-bot
    env: node
    plan: free
    repo: https://github.com/1Alusha1/network-leads-whatsapp
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    mounts:
      - name: wa-session
        path: /data

volumes:
  - name: wa-session
