services:
  - type: worker
    name: whatsapp-bot
    env: node
    repo: https://github.com/1Alusha1/network-leads-whatsapp
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    mounts:
      - name: wa-session
        path: /data
    envVars:
      - key: API_URI
        value: https://example.com/api

volumes:
  - name: wa-session
